### ISSUE TITLE
Missing page number in pagination if total page number is even and by 1 greater than visible pages

### ISSUE THREAD

**Issue by psmyrek** [vuestorefront/vsf-capybara#368]
## Current behavior

Missing page number in pagination if total page number is even and by 1 greater than visible pages.

## Expected behavior

First and last page numbers should be always displayed.

## Steps to reproduce the issue

1. Go to https://capybara.storefrontcloud.io/men/tops-men/tops-12?page=3
   Total page number is 4.
2. Click page number 2.
   Total page number is 3.

![pagination](https://user-images.githubusercontent.com/56868128/81787893-fa981c00-9501-11ea-9e97-e901d681ea0b.gif)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: any
- OS: any
- Code Version: latest

## Additional information
Issue probably related to https://github.com/DivanteLtd/storefront-ui/issues/1182

**Comment by dt2patel** [comment]
Issue seems to be resolved now. Closing.
