### ISSUE TITLE
Display attributes in product list

### ISSUE THREAD

**Issue by ArieRym** [vuestorefront/vsf-capybara#400]
**How to see selectively relevant attributes in a product area on a category page?**

![Women_Vue_Storefront](https://user-images.githubusercontent.com/20755897/84424426-b6518600-ac3d-11ea-8547-d78aca710d42.jpg)

For example, as in the magento 2 in product list page

![Bottoms_Women](https://user-images.githubusercontent.com/20755897/84425781-be122a00-ac3f-11ea-8037-efb738b00de4.jpg)

**Comment by ArieRym** [comment]
@gibkigonzo  Could you tell me

**Comment by ArieRym** [comment]
@gibkigonzo Hi! Could you tell me

**Comment by gibkigonzo** [comment]
Hey, you must pass it by props to your components. Probably it require changes in components also.

**Comment by dt2patel** [comment]
Closing since this is not part of Capybara design. Customize as suggested by gizbkigonzo
