### ISSUE TITLE
New VSF Capybara 1.0.2 doesn't show attributes on product page, Picture does not switch, Unclear numbers instead of the attribute name

### ISSUE THREAD

**Issue by ArieRym** [vuestorefront/vsf-capybara#428]
Installed a versions: Vue storefront api v1.12.1, Vue storefront 1.12.1, Capybara 1.0.2, Magento 2.3.5, but the attributes in the product card are missing
![Nadia-Elements-Shell-JVue-StorefrontB-Labaratory](https://user-images.githubusercontent.com/20755897/88370819-6f17f280-cdb0-11ea-9715-0a75b594ff01.jpg)

**Comment by AishwaryShrivastav** [comment]
Related to  #[386](https://github.com/DivanteLtd/vsf-capybara/issues/386)

**Comment by ArieRym** [comment]
The problem is that the attributes are missing (not displayed), the problem is in the code in the new version

**Comment by ArieRym** [comment]
@gibkigonzo Please help me figure it out

**Comment by ArieRym** [comment]
@gibkigonzo

**Comment by dt2patel** [comment]
Looks like attribute was added here. Images seem to be changing now. Please open a new issue for remaining issues if you are still facing them. Thanks.
