### ISSUE TITLE
Cannot remove items from micro cart panel

### ISSUE THREAD

**Issue by timberkeley** [vuestorefront/vsf-capybara#429]
## Current behavior

Click on the green X icon does nothing.

## Expected behavior

Expect the green x icon to remove an item from a cart when clicked

## Steps to reproduce the issue
On https://capybara.storefrontcloud.io/ add an item to the cart and then try and remove it.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: Chrome Version 84.0.4147.89, Firefox version 78.0.2
- OS: Ubuntu 18.04.4 LTS
- Code Version: How do you find the version of a running site?

**Comment by timberkeley** [comment]
Seems like you need the @click handler on the SfCircleIcon in SfCollectedProduct.vue
```javascript
      <SfCircleIcon
        icon="cross"
        aria-label="Remove"
        class="sf-circle-icon--small sf-collected-product__remove sf-collected-product__remove--circle-icon"
        @click="removeHandler"
      />
```
Not sure when the SfButton is used

**Comment by mohammad-k8** [comment]
Need to update the version of storefront-ui in package.json.
It is fixed here: https://github.com/DivanteLtd/storefront-ui/commit/96a160fde2800e7ed78982e1c81d353dc6bc112c

**Comment by dimasch** [comment]
Related to #459

**Comment by dt2patel** [comment]
Issue seems to be fixed now. Closing issue. Please make a new issue if this is still happening.
