### ISSUE TITLE
In Mobile view On clicking my profile user should land on my profile section instead of the page to update personal information.

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#446]
## Current behavior

On clicking my profile user lands on my page to update personal information.

## Expected behavior

On clicking my profile user should land on my profile section.

## Steps to reproduce the issue

Open capybara.storefrontcloud.io/
login with a user
click profile icon in bottom menu bar

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser:  All
- OS:  All
- Code Version:  All

## Additional information

As discussed in the slack channel https://vuestorefront.slack.com/archives/C8JMCHQ6S/p1597301163194000

**Comment by dt2patel** [comment]
Closing because this will have to be solved in SFUI.
