### ISSUE TITLE
Move order details from my profile to order tab in mobile view

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#447]
## Current behavior

In mobile view order details are in my profile section.

## Expected behavior

They should be in Order tab

## Steps to reproduce the issue

Open capybara.storefrontcloud.io/
login with a user
click profile icon in bottom menu bar.
click back arrow in My Profile heading. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

As discussed in the slack channel https://vuestorefront.slack.com/archives/C8JMCHQ6S/p1597301163194000

**Comment by dt2patel** [comment]
Will open a new issue if this is still needed.
