### ISSUE TITLE
irresponsive My Account Menu inside order Menu in Mobile

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#449]
## Current behavior

On clicking the My Account, user stays on the same page, neither it navigates to other page nor it moves up or down in page to go to proper menu

## Expected behavior

User should go to My Account section, maybe in the same page.

## Steps to reproduce the issue

Open capybara.storefrontcloud.io/
login with a user
click profile icon in bottom menu bar
press back icon in My Profile
scroll down, click orders tab
click on My Account menu.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
This is issue with SFUI component. Closing issue.
