### ISSUE TITLE
Micro cart panel doesn't correctly displayed in safari if bottom buttons are visible

### ISSUE THREAD

**Issue by iehoshia** [vuestorefront/vsf-capybara#460]
## Current behavior
In mobile version, safari, click on cart icon, the microcart-panel is open, but if the bottom buttons are visible the panel is not correctly displayed.

## Expected behavior
The micro cart panel correctly displayed. 

## Steps to reproduce the issue
Open the micro cart panel 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ x ] NO

## Environment details

- Browser: Safari, 13.6.1
- OS: iOS
- Code Version: VSF Capybara Theme

## Additional information

I think some css need to be added in 
https://github.com/DivanteLtd/vsf-capybara/blob/c46f43df003d8b19b78df31fbd7bb06ba9b3ce98/components/organisms/o-microcart-panel.vue#L68

![image](https://user-images.githubusercontent.com/4419325/91652103-2f989200-ea51-11ea-989f-329e99bae55c.png)

I attached a picture, the part in black is where the GoToCheck button is not displayed, but is the bottom button aren't visible GoToCheckout is correctly displayed. 

![image](https://user-images.githubusercontent.com/4419325/91652144-59ea4f80-ea51-11ea-9c6f-9c92cab5517c.png)

The max-height is not correctly calculed in the line if the bottom bar is visible. So the var(--bottom-navigation-height) need to be updated. 

Maybe it is related to: 
https://stackoverflow.com/questions/24889100/ios-8-removed-minimal-ui-viewport-property-are-there-other-soft-fullscreen/26884561#26884561

https://github.com/DivanteLtd/vsf-capybara/blob/c46f43df003d8b19b78df31fbd7bb06ba9b3ce98/components/organisms/o-microcart-panel.vue#L206

**Comment by dt2patel** [comment]
Behavior was fixed in this PR: #577
