### ISSUE TITLE
Spacing of elements inside search panel can be improved

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#473]
## Current behavior

There are some overridden padding which can be remove, H3 element is used for which we can use sfui heading.
Product card used under search panel also have some overriding of spacing properties. 

## Expected behavior

We can use most of the SFUI elements ootb without much overwritten css without having any visual change.
The search panel height on mobile can be full page

## Steps to reproduce the issue

Go to capybara.storefrontcloud.io/
Search some product

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser:  All
- OS:  All
- Code Version:  

## Additional information

![capybarasearch](https://user-images.githubusercontent.com/8766155/93024219-66a2a200-f612-11ea-9df3-7682390d2b41.png)

**Comment by dt2patel** [comment]
Does this issue have a PR for it? If not, and the work has been completed else where, I think you can link that here and close this issue.

**Comment by dt2patel** [comment]
Closing issue, spacing has since been fixed in another pr
