### ISSUE TITLE
Filter's icon color on category page

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#486]
## Current behavior

Its overridden with hardcoded values  

## Expected behavior

Instead of hardcoded values we can use sfui color variables 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
PR was closed. Will make a new ticket for this if we come back to this. Closing issue.
