### ISSUE TITLE
Mobile Menu subitems can't be selected like desktop menu

### ISSUE THREAD

**Issue by TTomas** [vuestorefront/vsf-capybara#506]
## Current behavior

Mobile menu can't select Women-Tops-Jackets like desktop version. Example category from https://capybara.storefrontcloud.io/
I have a lot of category's in 3 level of menu.

## Expected behavior

Mobile menu to reach all category's like desktop version

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
Closing this issue because this will have to be fixed in SFUI, and lack of activity. Thank you.
