### ISSUE TITLE
Display by which option products are sorted in category page [Mobile]

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#508]
## What is the motivation for adding/enhancing this feature?

In the category page, the user is not able to see by which option the products are sorted. 

![sortby ](https://user-images.githubusercontent.com/8766155/94773930-6fe58a00-03da-11eb-8d6b-33eca1cb1188.png)

## What are the acceptance criteria?

We can display the current sorted option to user,instead of sort by text 

## Can you complete this feature request by yourself?

- [X] YES
- [ ] NO

## Additional information

As per the conversation on this [PR](https://github.com/DivanteLtd/vsf-capybara/pull/469)

**Comment by dt2patel** [comment]
Closing since we won't be introducing re designs.
