### ISSUE TITLE
Cannot remove product from sidebar cart

### ISSUE THREAD

**Issue by daksamit** [vuestorefront/vsf-capybara#522]
update: comment below

## Current behavior

Clicking (x) on SfCollectedProduct does nothing
![image](https://user-images.githubusercontent.com/7165997/95725709-4c42ff00-0c78-11eb-8855-774cbbcae55e.png)

## Expected behavior

Item should be removed from cart after clicking (x)

## Steps to reproduce the issue

Check on https://capybara.storefrontcloud.io/ or develop branch after adding any product from catalog and open cart

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

I think it's related to `removeHandler` on `@click:remove` at `components/organisms/o-microcart-panel.vue`

**Comment by daksamit** [comment]
Ok, I now the solution.
It seems to be bug caused by old storefront-ui version.
current version on develop branch is `0.7.11` and the latest version is `0.9.1`

Could it be hard to refactor capybara to latest sf-ui ?

**Comment by dt2patel** [comment]
I am currently not able to reproduce this issue on Capybara demo instance. Please open a new issue and link this if this is still happening. Thanks!
