### ISSUE TITLE
Some links are not acting like router-link but a href links

### ISSUE THREAD

**Issue by mrinc** [vuestorefront/vsf-capybara#529]
## Current behavior
Certain links on the site, like going to categories are reloading the page instead of navigating like an SPA.

## Expected behavior
Navigate and not browser navigate

## Steps to reproduce the issue
Just use the site

## Can you handle fixing this bug by yourself?

- [ X] YES
- [ ] NO

## Environment details
- Browser: Firefox 82.0.2
- OS: Windows
- Code Version: develop as of now.

## Additional information
Just creating this issue for reference purposes.
I'll work on the fix and make sure nav is working properly so it's not effecting the site I am currently working on.

**Comment by dt2patel** [comment]
Hi @mrinc looks like this issue is no longer happening on the latest demo. Did you resolve this in a PR? If you, care to link it to this issue and closing it?

**Comment by dt2patel** [comment]
Cannot re produce issue. Closing issue.
