### ISSUE TITLE
Give minimum height to all pages

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#538]
## What is the motivation for adding/enhancing this feature?

Giving minimum height to all the pages will make the footer intact and not overflow in initial fold

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [X] YES
- [ ] NO

**Comment by dt2patel** [comment]
Duplicate issue. Will handle in #503
