### ISSUE TITLE
iOS zooms into input fields

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#542]
## Current behavior

Font size is less than 16px, due to which safari zooms into that input box

## Expected behavior

We can inc the size to base

## Steps to reproduce the issue

1. Open capaybara website on ios mobile
2. Click on search 
3. Select input box of search

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser:  Safari
- OS:  iOS
- Code Version:  All

**Comment by dt2patel** [comment]
The title here is not the issue. Add a relevant title.
