### ISSUE TITLE
Capybara demo not working

### ISSUE THREAD

**Issue by michaelKurowski** [vuestorefront/vsf-capybara#559]
## Current behavior
Capybara demo instance has no products

## Expected behavior
Capybara demo should be functional

## Steps to reproduce the issue
Enter demo instance, start navigating through pages

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: N/A
- OS: N/A
- Code Version: Demo instance

## Additional information
N/A

**Comment by michaelKurowski** [comment]
@daksamit FYI

**Comment by janiek** [comment]
Already down for a couple of weeks now...

**Comment by CombatCode** [comment]
"Ready for production", hueh, nothing is working here, waste of time.

**Comment by dt2patel** [comment]
A new version release is imminent and along with that the demo site will also be fixed

**Comment by Fifciu** [comment]
I've just merged 1.0.4 version to the `master` branch and deployed it on the demo. Since now it works: https://capybara.storefrontcloud.io/

Please make sure to purge your browser's cache
