### ISSUE TITLE
Products tiles spacing can be improved in the search panel for mobile view

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#574]
## Current behavior

Single product comes in search panel for mobile view

## Expected behavior

Spacing should be utilised well

## Steps to reproduce the issue

Open capybara in mobile device
Click on search 
search any keyword [Yoga]

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser:  All
- OS:  All
- Code Version:  Develop

**Comment by dt2patel** [comment]
The actual issue: There is too much padding on the search panel on mobile, causing flex wrap to only show one item per row on iPhone X devices. The fix for this is to remove the mobile specific padding writing on the container.

**Comment by dt2patel** [comment]
Fixed in #615
