### ISSUE TITLE
Update the SFUI version in Capybara

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#582]
## What is the motivation for adding/enhancing this feature?

Currently, we're using 0.7.11 version of SFUI, and there's a lot of new elements and bug fixes introduced in the latest version 

## What are the acceptance criteria?

On upgrading the SFUI version we need to fix many small UI bugs which will be there due to change in the library

- [ ] ...

## Can you complete this feature request by yourself?

- [X] YES
- [ ] NO

## Additional information

As per the discussion with @Fifciu and also in the [community](https://vuestorefront.slack.com/archives/CA68P1JUF/p1611659777098500)

**Comment by AishwaryShrivastav** [comment]
Mega Menu
![Screenshot from 2021-02-01 17-18-11](https://user-images.githubusercontent.com/8766155/106455494-49337f00-64b2-11eb-9345-c114f4dff567.png)

Home page main carousel
![Screenshot from 2021-02-01 17-18-16](https://user-images.githubusercontent.com/8766155/106455526-52bce700-64b2-11eb-8d5d-f1f80cf7f088.png)

Home page product carousel
![Screenshot from 2021-02-01 17-18-26](https://user-images.githubusercontent.com/8766155/106455566-5f413f80-64b2-11eb-935b-6f28ed79cc7a.png)

Share your look section
![Screenshot from 2021-02-01 17-18-39](https://user-images.githubusercontent.com/8766155/106455622-72eca600-64b2-11eb-8aa6-ba37cb2b6df2.png)

Category page navbar
![Screenshot from 2021-02-01 17-19-01](https://user-images.githubusercontent.com/8766155/106455663-813ac200-64b2-11eb-91d3-4680ed043113.png)


Product page main image
![Screenshot from 2021-02-01 17-19-30](https://user-images.githubusercontent.com/8766155/106455702-8e57b100-64b2-11eb-9fc6-a20affa1c6a9.png)

Form in checkout section

![Screenshot from 2021-02-01 17-21-19](https://user-images.githubusercontent.com/8766155/106455745-9b74a000-64b2-11eb-9135-785752ea4fb6.png)

Review section in checkout process
![Screenshot from 2021-02-01 17-22-01](https://user-images.githubusercontent.com/8766155/106455771-a62f3500-64b2-11eb-8468-2eea3bb0cfef.png)

![Screenshot from 2021-02-01 17-22-20](https://user-images.githubusercontent.com/8766155/106455806-b21af700-64b2-11eb-9e8a-0d85e286f005.png)

Footer
![Screenshot from 2021-02-01 17-22-40](https://user-images.githubusercontent.com/8766155/106455824-b9da9b80-64b2-11eb-81a4-14d9c83a77c5.png)

**Comment by AishwaryShrivastav** [comment]
Here is [link](https://drive.google.com/file/d/1OlP8hmwtErVcCg3S8kBjy_lVT8Ad4tV_/view?usp=sharing) for full overview after upgrading

**Comment by ke-real** [comment]
Is Capybara a dead project? should we expect any updates further on?

**Comment by FaustTobias** [comment]
This theme is such a pain to work with. The documentation is not nearly as concise as it could be and the dependencies are pretty much outdated to a point where this theme is almost unusable. Calling it "prodution ready" unfortunately seems not to be possible at its current state :(

**Comment by AishwaryShrivastav** [comment]
Hey @ke-real , definitely its not! 

The above screenshots are after we update a specific dependency(SFUI), on which capybara heavily relies.
This issue if for upgrading a dependency. 

There will be more updates and stable releases.
In case you're looking for some specific fix, you may find it in the pull requests and if not, feel free to create an issue around it.

**Comment by dt2patel** [comment]
Closing since we will jump to 0.11 which is the latest version. Will make a new issue for that.
