### ISSUE TITLE
Menu navigation does not work after using category pagination

### ISSUE THREAD

**Issue by raulmarvan** [vuestorefront/vsf-capybara#583]
## Current behavior
The url changes but the products are not updated when using the pagination of a category and then the category is changed.

## Expected behavior
It is expected that the route will change and that the products of the new selected category will load.

## Steps to reproduce the issue
1. Go to any category that has pagination
2. Advance to any next page in the category pagination
3. Try going to a different category

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details
- Browser: Google Chrome
- OS: Windows 10
- Code Version:

## Additional information
![bug_vsf_capybara](https://user-images.githubusercontent.com/71658619/106540295-442bfb00-64c5-11eb-9478-cfc900cfc105.gif)

**Comment by micheldenegri** [comment]
This was fixed in this PR: #564 you can close this ticket. Thank you @Fifciu for pointing it out.
