### ISSUE TITLE
I get an error when placing an order

### ISSUE THREAD

**Issue by wmycco1** [vuestorefront/vsf-capybara#658]
I have installed https://github.com/danrcoull/vsf-payment-braintree.

Through front, everything works, both braintree and paypal, but when I try to checkout through capybara, nothing happens during checkout and there is only one error in the console TypeError: Cannot read property 'addEventListener' of null

Could not load content for webpack: ///vsf-checkout.922af10f3d0a88c39031.js (HTTP error: status code 404, net :: ERR_UNKNOWN_URL_SCHEME) 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X ] NO

## Environment details

- Browser: Google Chrome Version 91.0.4472.114 
- Code Version: 
- Vue Storefront 1.12.2
- Vue Storefront 1.12.3
- VSF Capybara 1.0.3
- Magento ver. 2.3.5-p1

![image](https://user-images.githubusercontent.com/71315301/123934475-f0103e80-d9b0-11eb-88c3-f56b57e4d079.png)

Or in a new version without caching
- Browser: Google Chrome Version 91.0.4472.114 
- Code Version: 
- Vue Storefront 1.12.3
- Vue Storefront Api 1.12.4
- VSF Capybara 1.0.5
- Magento ver. 2.3.5-p1

![image](https://user-images.githubusercontent.com/71315301/124000952-bdd30100-d9f1-11eb-9c9c-ea8957e84db3.png)

![image](https://user-images.githubusercontent.com/71315301/124000982-c4617880-d9f1-11eb-9824-77add7ef35f3.png)

![image](https://user-images.githubusercontent.com/71315301/124001525-58334480-d9f2-11eb-8ccd-94fbe1a09bab.png)

**Comment by Fifciu** [comment]
This issue is related to neither vsf1 nor vsf-capybara. It is related to vsf-payment-braintree
