### ISSUE TITLE
Position of sort by drop down moved upwards due to backdrop filter

### ISSUE THREAD

**Issue by azkyakhan** [vuestorefront/vsf-capybara#669]
## Current behavior
Position of sort by drop down moved upwards due to backdrop filter

## Expected behavior
Position should be at the bottom

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
PR merged, closing issue
