### ISSUE TITLE
I want to see add review modal based on design

### ISSUE THREAD

**Issue by gibkigonzo** [vuestorefront/vsf-capybara#87]
Right now there is added simple modal for that:
![Zrzut ekranu z 2020-01-23 08-37-49](https://user-images.githubusercontent.com/42383376/73631074-35173080-4658-11ea-804a-cf5309004757.png)
We need to update this when there will be design.

**Comment by dt2patel** [comment]
Closing since designs have since been updated and no longer have this design.
